export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  mpesaConsumerKey: process.env.MPESA_CONSUMER_KEY ?? "",
  mpesaConsumerSecret: process.env.MPESA_CONSUMER_SECRET ?? "",
  mpesaShortcode: process.env.MPESA_SHORTCODE ?? "",
  mpesaPasskey: process.env.MPESA_PASSKEY ?? "",
  mpesaCallbackUrl: process.env.MPESA_CALLBACK_URL ?? "",
  africasTalkingApiKey: process.env.AFRICAS_TALKING_API_KEY ?? "",
  africasTalkingUsername: process.env.AFRICAS_TALKING_USERNAME ?? "",
  africasTalkingSenderId: process.env.AFRICAS_TALKING_SENDER_ID ?? "",
};
